name: build

on: 
  push:
    paths: 
      - ExtendUnityActivity/app/**
      - .github/workflows/build_activity.yml

jobs:
   build_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - run: echo "Setting up JDK" 
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - run: echo "The workflow is now ready to test your code."
    - name: Grant execute permission for gradlew
      run: chmod +x ./ExtendUnityActivity/gradlew
    - run: echo "Building Release AAR."  
    - name: Build with Gradle
      run: |
        cd ExtendUnityActivity
        ./gradlew build
    - run: echo "Build status report=${{ job.status }}."

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: ./ExtendUnityActivity/app/build/outputs/aar
        name: output_arr